---
- name: Tags Validation
  hosts: localhost
  become: false
  gather_facts: false
  tasks:
    - name: Validate tags
      ansible.builtin.fail:
        msg: "Invalid tag(s): {{ ansible_run_tags | difference(global_map.tags.role | union(['validation'])) | join(', ') }}"
      tags: always
      when:
        - ansible_run_tags not in [[], ['all']]
        - ansible_run_tags | difference(global_map.tags.role | union(['validation'])) | length > 0

- name: Cluster Validation
  hosts: cluster
  become: true
  gather_facts: true
  tasks:
    - name: Validate global settings
      ansible.builtin.include_role:
        apply:
          tags: '{{ validation }}'
        name: '{{ validation }}'
        tasks_from: validation
      loop: '{{ global_map.tags.role }}'
      loop_control:
        loop_var: validation
      tags: always
      when: (ansible_run_tags == ['all']) or (validation in ansible_run_tags)
