name: Documentation

on:
  pull_request:
    paths:
      - roles/*/defaults/main.yaml
      - roles/*/Chart.yaml
      - roles/*/README.md.gotmpl

concurrency:
  cancel-in-progress: true
  group: ${{ github.workflow }}-${{ github.ref }}

defaults:
  run:
    shell: bash

permissions:
  contents: write
  issues: write

jobs:
  update:
    name: Update
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Install node dependencies
        run: npm install handlebars

      - name: Configure repository
        uses: actions/github-script@v7
        with:
          script: |
            const { configureGitRepository } = require('./.github/scripts/utils.js');
            await configureGitRepository({ github, context, core, exec });

      - name: Install helm-docs
        uses: actions/github-script@v7
        with:
          script: |
            const { installHelmDocs } = require('./.github/scripts/documentation.js');
            await installHelmDocs({ core, exec, version: '1.14.2' });

      - name: Update documentation
        uses: actions/github-script@v7
        with:
          script: |
            const { updateDocumentation } = require('./.github/scripts/documentation.js');
            await updateDocumentation({ github, context, core, exec });

      - name: Report workflow issue
        uses: actions/github-script@v7
        with:
          script: |
            const { reportWorkflowIssue } = require('./.github/scripts/utils.js');
            await reportWorkflowIssue({ github, context, core });
